apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::<ACCOUNT_ID>:user/<USERNAME>
      username: <USERNAME>
      groups:
        - system:masters
    - userarn: arn:aws:iam::<ACCOUNT_ID>:user/github-user
      username: github-user
      groups:
        - eks:deployer
