apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::974085360964:user/Oreoluwa
      username: Oreoluwa
      groups:
        - system:masters
    - userarn: arn:aws:iam::974085360964:user/github-user
      username: github-user
      groups:
        - eks:deployer
