apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-backend-deployment
  labels:
    app: {{ .Values.simpleAppBackend.app.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.simpleAppBackend.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.simpleAppBackend.app.name }}
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Values.simpleAppBackend.app.name }}
          image: {{ .Values.simpleAppBackend.image.repository }}:{{ .Values.simpleAppBackend.image.tag }}
          ports:
            - containerPort: 4000
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_HOST
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_NAME
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_PORT
