apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-backend-deployment
  labels:
    app: simple-app-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-app-backend
  template:
    metadata:
      labels:
        app: simple-app-backend
    spec:
      serviceAccountName: default
      containers:
        - name: backend
          image: 974085360964.dkr.ecr.eu-north-1.amazonaws.com/simple-app-backend:e08c2f3514aef159f1c3d0899a909df594d02f10-2025-05-22-11-22
          ports:
            - containerPort: 4000
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_HOST
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_NAME
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_PORT
