apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_HOST: dGVycmFmb3JtLTIwMjUwNzE3MTQzMzQ3NTQyNDAwMDAwMDAxLmNsOHV3MjhxY21vbC5ldS1ub3J0aC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USER: YWRtaW4=
  DB_PASSWORD: QWRtaW5wYXNzd29yZDIwMDQh
  DB_NAME: bXlkYg==
###This database does not currently exist


