apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: simple-app-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30002
  type: NodePort
