apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_HOST: dGVycmFmb3JtLTIwMjUwNzE3MTQzMzQ3NTQyNDAwMDAwMDAwMS5jbDh1dzI4cWNtb2wuZXUtbm9ydGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  DB_USER: YWRtaW4=
  DB_PASSWORD: QWRtaW5wYXNzd29yZDIwMDQh
  DB_NAME: bXlkYg==
###This database does not currently exist
