apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-frontend-deployment
  labels:
    app: simple-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app-frontend
  template:
    metadata:
      labels:
        app: simple-app-frontend
    spec:
      serviceAccountName: default
      containers:
        - name: frontend
          image: 974085360964.dkr.ecr.eu-north-1.amazonaws.com/simple-app-frontend:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
