apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-frontend-deployment
  labels:
    app: {{ .Values.simpleAppFrontend.app.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.simpleAppFrontend.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.simpleAppFrontend.app.name }}
    spec:
      serviceAccountName: default
      containers:
        - name: frontend
          image: {{ .Values.simpleAppFrontend.image.repository }}:{{ .Values.simpleAppFrontend.image.tag }}
          ports:
            - containerPort: 3000
