# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-deployer
  namespace: default
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "services", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deployer-binding
  namespace: default
subjects:
  - kind: User
    name: github-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: github-deployer
  apiGroup: rbac.authorization.k8s.io
