simpleAppFrontend:
  image:
    repository: 974085360964.dkr.ecr.eu-north-1.amazonaws.com/simple-app-frontend
    tag: 8916ba341bbc432355eedf48ec6ef8bab5936470-2025-06-03-10-11
app:
  name: simple-app-frontend
